apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-k8s-auth
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-k8s-auth
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-k8s-auth
