loki:
  commonConfig:
    replication_factor: 1
  ingester:
    lifecycler:
      ring:
        replication_factor: 1
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: s3
    s3:
      endpoint: "https://storage.yandexcloud.net"
      region: "ru-central1"
      s3ForcePathStyle: true
      accessKeyId: "${S3_ACCESS_KEY_ID}"
      secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
    bucketNames:
      chunks: "otus-logs-1754956948"
      ruler:  "otus-logs-1754956948"
      admin:  "otus-logs-1754956948"

  limits_config:
    retention_period: 168h

extraArgs:
  - "-config.expand-env=true"

nodeSelector:
  node-role: "infra"
tolerations:
  - key: "node-role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

env:
  - name: S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: loki-s3
        key: access_key_id
  - name: S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: loki-s3
        key: secret_access_key

service:
  type: ClusterIP

read:
  replicas: 1
  nodeSelector: { node-role: "infra" }
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

write:
  replicas: 1
  nodeSelector: { node-role: "infra" }
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"

backend:
  replicas: 1
  nodeSelector: { node-role: "infra" }
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"