apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: debug
  labels:
    app: nginx-distroless
spec:
  shareProcessNamespace: true
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
    - name: nginx
      image: kyos0109/nginx-distroless:latest
      ports:
        - containerPort: 80
    - name: dbg
      image: nicolaka/netshoot
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        capabilities:
          add: ["SYS_PTRACE","NET_ADMIN","NET_RAW"]
      command: ["bash","-lc","sleep infinity"]
