apiVersion: v1
kind: Service
metadata:
  name: nginx-distroless
  namespace: debug
spec:
  selector:
    app: nginx-distroless
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
