loki:
  enabled: true

promtail:
  enabled: true

  extraScrapeConfigs:
    - job_name: kubernetes-pods-ingress-json
      pipeline_stages:
        - cri: {}
        - json:
            expressions:
              status: status
              method: method
              path: path
              upstream_status: upstream_status
              request_time: request_time
        - labels:
            status:
            method:
            upstream_status:
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io/name]
          regex: ingress-nginx
        - action: keep
          source_labels: [__meta_kubernetes_pod_container_name]
          regex: controller
        - action: replace
          source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node

datasource:
  enabled: false