loki:
  enabled: true

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - match:
            selector: '{namespace="ingress-nginx", container="controller"}'
            stages:
              - json
              - labels:
                  status:
                  method:
                  path:
                  host:
              - metrics:
                  - type: Counter
                    name: nginx_requests_total
                    description: "nginx requests"
                    labels: {status: "", method: "", host: ""}
                    value: 1

datasource:
  enabled: false