replicaCount: 2

image:
  repository: nginx
  tag: "1.25.4-alpine"

serviceAccount:
  create: true
  name: monitoring

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false      # включишь при желании

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  node-role: "workload"

tolerations: []
affinity: {}