apiVersion: v1
kind: Service
metadata:
  name: homework-nginx-svc
  namespace: default
  labels:
    app: homework-nginx
spec:
  selector:
    app: homework-nginx
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework-nginx
  template:
    metadata:
      labels:
        app: homework-nginx
    spec:
      containers:
        - name: nginx
          image: dvoryankin/nginx-with-metrics:v1.0
          ports:
            - containerPort: 80
              name: web

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          args:
            - "-nginx.scrape-uri=http://localhost/stub_status"
          ports:
            - containerPort: 9113
              name: metrics