apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homework-nginx-sm
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: homework-nginx
  endpoints:
    - port: metrics
      interval: 15s