apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics/*"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes/metrics", "pods/metrics"]
  verbs: ["get", "list"]