kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kuber-pvc
  namespace: homework
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
