apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: homework
  labels:
    app: nginx-homework
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: nginx-homework-pod