apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
  labels:
    app: nginx-homework
spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-homework-pod

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: nginx-homework-pod
    spec:
      nodeSelector:
        homework: "true"

      initContainers:
        - name: init-download
          image: busybox:1.36
          command:
            - sh
            - -c
            - "wget -O /init-data/index.html http://example.com && chmod +r /init-data/index.html"
          volumeMounts:
            - name: shared-html-data
              mountPath: /init-data

      containers:
        - name: web
          #image: nginx:1.25.4-alpine
          image: nginx:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-html-data
              mountPath: /homework
          lifecycle:
            preStop:
              exec:
                command: ["rm", "-f", "/homework/index.html"]

          readinessProbe:
            exec:
              command:
                - test
                - -e
                - /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

      volumes:
        - name: shared-html-data
          emptyDir: {}
