apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homework-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homework-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "monitoring" }}
      containers:
        - name: {{ include "homework-chart.name" . }}
          image: {{ .Values.image.repository | default "nginx" }}:{{ .Values.image.tag | default "1.25.4-alpine" }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared-html-data
              mountPath: /usr/share/nginx/html
            {{- if .Values.configMap.enabled }}
            - name: config-volume
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      initContainers:
        - name: init-index
          image: busybox:1.36
          command: [ "sh","-c","echo 'Hello from GitOps (Helm)!' > /init-data/index.html" ]
          volumeMounts:
            - name: shared-html-data
              mountPath: /init-data
      nodeSelector:
        node-role: "workload"
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: shared-html-data
          emptyDir: {}
      {{- end }}