apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "homework-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homework-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html
            {{- if .Values.configMap.enabled }}
            - name: config-volume
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
        {{- if .Values.configMap.enabled }}
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: {{ .Values.configMap.mountKey }}
                path: {{ .Values.configMap.mountFile }}
        {{- end }}
      {{- end }}