apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework
  labels:
    app: nginx-homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-homework-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-homework-pod
    spec:
#      nodeSelector:
#        homework: "true"

      initContainers:
        - name: init-download
          image: busybox:1.36
          command:
            - sh
            - -c
            - "wget -O /mnt/data/index.html http://example.com && chmod +r /mnt/data/index.html"
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/data

      containers:
        - name: web
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html
            - name: config-volume
              mountPath: /homework/conf
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command: ["echo", "PreStop hook: Not removing index.html from PVC"]
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: kuber-pvc

        - name: config-volume
          configMap:
            name: kuber-cm
            items:
              - key: "dbuser"
                path: "file"