name: build-and-deploy

on:
  push:
    branches: [ main, project/managed-shop-otus ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: project/src/frontend/Dockerfile
          platforms: linux/amd64
          push: false

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Write kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Rollout status
        run: kubectl -n default rollout status deploy/frontend --timeout=180s