apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  containers:
    - name: web
      image: nginx:1.25.4-alpine
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-data
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/homework/index.html"]
  initContainers:
    - name: init-download
      image: busybox
      command:
        - sh
        - -c
        - 'wget -O /init/index.html https://example.com'
      volumeMounts:
        - name: shared-data
          mountPath: /init
  volumes:
    - name: shared-data
      emptyDir: {}
