apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-kubernetes-templating
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-04OTUS/dvoryankin_repo
    targetRevision: HEAD
    path: kubernetes-templating/homework-chart
    helm:
      parameters:
        - name: replicaCount
          value: "2"
  destination:
    server: https://kubernetes.default.svc
    namespace: homework-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true